string=input("Enter a string: ")
print("Fifth position of the string: ", string[4])
print("First 3 characters in the strings: ", string[:3])
print("Reverse of the string: ", string[::-1])
print(string[1:5]) # another type of slicing
print("second positio charactors of the string:", string[::2])
print("Backword second position: ", string[::-2])
print("backward from specific position: ", string[5::-2])
print("Length of the string: ", len(string))
print("Lower case of the string: ", string.lower())
print("Upper case of the string: ", string.upper())
print("character replace in the string: ", string.replace('h', ''))
print("split the given string: ", string.split())
print("List of charactors in the given string: ", list(string))
print("List to string: ", "".join(list(string)))
print("Join method: ","".join(['a', 'b']))
print("Count specific charactors in a string: ", string.count('a'))