# Generated by Django 5.2.15 on 2026-06-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("Name", models.CharField(primary_key=10, serialize=False)),
                ("age", models.IntegerField()),
            ],
        ),
    ]
