lst=list(map(int, input("Enter a list of elements: ").split()))
print("First position element on the list is : ", lst[0])
print("Fifth position element in the list is : ", lst[4])
print("list slicing: ", lst[0:4])
b=lst.append(25)
print("List append: ", lst)
c=lst.insert(2, 0.25)
print("List insert: ", lst)
lst.remove(0.25)
print("List remove: ", lst)
print("POP of the list: ",lst.pop())
lst.sort()
print("Sort of the list: ", lst)
lst.reverse()
print("Reverse of the list: ",lst)